spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seller_db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:123456}
   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
