spring:
  config:
    active:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
#---
spring:
  config:
    active:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
