spring:
  config:
    active:
      on-profile: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/seller_db
    username: sa
    password: 123456
   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

---
spring:
  config:
    active:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/seller_db
    username: sa
    password: 123456
