eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
      probes:
        enabled: true
