eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

management:
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
      probes:
        enabled: true
